ERR_OK = 0

# TODO: Reclassify number
ERR_SERIAL_OPEN_FAIL = -1
ERR_SERIAL_NOT_OPENED = -2

'''args parsing errcode'''
ERR_MISS_COM_INFO = -3
ERR_MISS_ADDRESS_INFO = -4
ERR_MISS_FILE_INFO = -5
ERR_MISS_SAVE_FILE_ARGS = -6
ERR_MISS_ERASE_ARGS = -7
ERR_MISS_M_FLAG = -8
ERR_MISS_EVT_FLAG = -9
ERR_HCI_ALIVE_NOT_UNDER_M_0 = -10

ERR_JSON_PARSE = -11
ERR_PACKED_IMG_FMT = -12
ERR_BT_MAC_INVALID = -13
ERR_INVALID_MODIFY_VALUE = -14
ERR_DBG_PASSWD_FORMAT_INVALID = -15

'''errcod in main line procedure'''
ERR_INI_CFG_PARSE_FAIL = -100
ERR_UNSUPPORTED_MODE = -101
ERR_CREATE_ARGS = -102
ERR_GET_CMD_HDL_FAIL = -103

ERR_DOWNLOAD_IMG_FAIL = -104
ERR_ERASE_FAIL = -105
ERR_SAVE_FAIL = -106
ERR_MODIFY_FAIL = -107
ERR_ADD_MAC_FAIL = -108
ERR_REBOOT_FAIL = -109
ERR_VERIFY_FAIL = -110

'''data uart errcode'''
ERR_CRC_CHK_FAIL = -200
ERR_DATA_UART_WRITE_FAIL = -201
ERR_DATA_UART_STATUS_FAIL = -202
ERR_DATA_UART_READ_FAIL = -203
ERR_REV_UNEXPECTED_RSP_CMD_CODE = -204
ERR_GENERATE_CMD_FAIL = -205
ERR_APP_NOT_IN_CLI_MODE = -206
ERR_CON_MP_LOAD_IN_FSBL = -207
ERR_AUTHEN_THROUGH_PASSWD_FAIL = -208
ERR_DATA_UART_FLASH_INIT_FAIL = -209
ERR_DATA_UART_FLASH_LOAD_FAIL = -210
ERR_DATA_UART_LOAD_RAM_PATCH_FAIL = -211
ERR_GET_APP_CLI_HELP_FAIL = -212
ERR_REV_INVALID_START_FLAG = -213
ERR_STATUS_AUTH_FAIL = -214


'''hci uart errcode'''
ERR_HCI_FLASH_INIT_FAIL = -301
ERR_HCI_FLASH_LOAD_CFG_FAIL = -302
ERR_HCI_FLASH_UNLOCK_FAIL = -303
ERR_HCI_NOT_SUPPORT_BAUDRATE = -304
ERR_HCI_SEND_DATA_FAIL = -305
ERR_HCI_EVT_LEN = -306
ERR_HCI_EVT_OPCODE = -307
ERR_HCI_EVT_CMD = -308
ERR_HCI_EVT_PKT_TYPE = -309
ERR_HCI_EVT_STATUS = -310
ERR_HCI_READ_FAIL = -311
ERR_HCI_READ_DATA_SHORT = -312
ERR_HCI_VERIFY_CRC_FAIL = -313
ERR_GET_ROM_MAGIC_FAIL = -314
ERR_GET_FW_LDR_INFO_FAIL = -315
ERR_FW_IMG_NOT_EXIST = -316
ERR_FW_IMG_SIZE_ZERO = -317
ERR_FW_IMG_SIZE_NOT_4_ALIGNED = -318
ERR_HCI_EVT_MISMATCH = -319
ERR_HCI_LOAD_FACTORY_MP_FAIL = -320

'''procedure errcode'''
ERR_FILE_NOT_EXIST = -400
ERR_IMG_NOT_PARSED = -401
ERR_FILE_OPEN_FAIL = -402
ERR_IMG_SIZE_ZERO = -403
ERR_PROGRAM_OBJ_NONE = -404
ERR_SAVE_OBJ_NONE = -405
ERR_IMG_DL_CONTENT_EMPTY = -406

ERR_ENTER_DBG_PASSWORD_FAIL = -407
ERR_GET_DBG_BOARD_PORT_FAIL = -408
ERR_DBG_BOARD_ENTER_HCI_MODE_FAIL = -409
ERR_IMG_ID_MISMATCH = -410
ERR_FLASH_READ_FAIL = -411
ERR_FLASH_DOWNLOAD_FAIL = -412
ERR_IMG_PARSE_FAIL = -413
ERR_IMG_SIZE_EXCEED_FLASH_SIZE = -414
ERR_OEM_CFG_EMPTY = -415
ERR_OEM_CFG_LEN_MISMATCH = -416

ERR_RUN_INTO_MP_LOADER = -417
ERR_HANDSHAKE_RSP_CHECK_FAIL = -418
ERR_SPIC_SELECT_FAIL = -419

ERR_FLASH_PATCH_ABNORMAL = -420
ERR_NOT_SUPPORT_LOAD_RP = -421
ERR_GET_CLI_CMD_FAIL = -422
ERR_CLI_LOAD_RP_FAIL = -423
ERR_WITH_SLOT_NOT_IN_HCI_MODE = -424
ERR_CANNOT_ENTER_HCI_AUTOMATIC = -425
ERR_ERASE_PROTECTION_SPACE = -426
ERR_NOT_SUPPORT_CLI_BUD_REBOOT = -427
ERR_FLASH_RDID_NOT_SUPPORTED = -428
ERR_EFUSE_WRITTEN_LEN_MISMATCH = -429
ERR_OEM_MODULE_ID_INVALID = -450
ERR_OEM_CFG_MODULE_LEN_INVALID = -451
ERR_OEM_MODULE_SIGNATURE_INVALID = -452
ERR_INVALID_PARAM = -453
ERR_PROGRAM_RSP_FAIL = -454
ERR_CMD_NOT_SUPPORT=-455
ERR_REV_UNEXPECTED_PARALLEL_RSP_INFO = -456
ERR_GET_BLOCK_SIZE_UNKNOWN = -457
