
'''
    mp status reference
'''
MP_STATUS_OK = 0x00

MP_STATUS_CMD_VERIFY_FAIL = 0x10
MP_STATUS_CMD_AUTH_FAIL = 0x11
MP_STATUS_CMD_BUFFER_OVFL = 0x12

MP_STATUS_PAGE_ERASE_FAIL = 0x31

MP_STATUS_PROGRAM_FAIL = 0x33
MP_STATUS_FLASH_VERIFY_FAIL = 0x34
MP_STATUS_PROGRAM_CHECK_FAIL = 0x35
MP_STATUS_ADDR_RANGE_CHK_FAIL = 0x36

STATUS_FLASH_INIT_FAIL = 0x37,
STATUS_FLASH_LOAD_CFG_FAIL = 0x38,
STATUS_FLASH_IDX_INVALID = 0x39,
STATUS_FLASH_READ_PARA_INVALID = 0x3A,
STATUS_FLASH_READ_FAIL = 0x3B,
STATUS_ALLOC_MEM_FAIL = 0x3F,

MP_STATUS_REBOOT_FAIL = 0x42

MP_STATUS_RP_RANGE_CHK_FAIL = 0x50

MP_STATUS_FAIL = 0x01