/**
 * LVGL component code generator interface
 */
import { Component } from '../../hml/types';
import { LvglResourceManager } from './LvglResourceManager';

/**
 * Generator context: provides shared state and utility methods across components
 */
export interface LvglGeneratorContext {
  /** Component ID → Component mapping */
  componentMap: Map<string, Component>;
  /** Get parent component reference variable name */
  getParentRef(component: Component): string;
  /** Unified resource manager */
  resources: LvglResourceManager;
  /** Get built-in image variable name (images converted to C arrays) - backward compatible, delegates to resources */
  getBuiltinImageVar(source: string): string | undefined;
  /** Get built-in font variable name (fonts converted to LVGL format) - backward compatible, delegates to resources */
  getBuiltinFontVar(fontFile: string, fontSize: number): string | null;
  /** Look up ancestor container's background color */
  getAncestorBackgroundColor(component: Component): string | null;
}

/**
 * LVGL component code generator interface
 * Each component type implements this interface
 */
export interface LvglComponentCodeGenerator {
  /**
   * Generate component creation + property setup code (inside ui_create function body)
   * Returned code includes indentation (4 spaces)
   */
  generateCreation(component: Component, parentRef: string, ctx: LvglGeneratorContext): string;

  /**
   * Generate event callback function code (outside ui_create function body, at file top)
   * Optional, not generated by default
   */
  generateEventCallbacks?(components: Component[]): string;

  /**
   * Generate global style/variable definitions (outside ui_create function body)
   * Optional, not generated by default
   */
  generateGlobalDefinitions?(components: Component[]): string;
}
