/**
 * ROMFS 生成工具 - TypeScript 实现
 * 将资源目录转换为 C 代码或二进制文件
 */

import * as fs from 'fs';
import * as path from 'path';

const ALIGNMENT_4 = 4;
const ALIGNMENT_64 = 64;

interface RomfsOptions {
    inputDir: string;
    outputFile: string;
    baseAddr?: number;
    binary?: boolean;
}

/**
 * 填充到指定对齐
 */
function padToAlignment(data: Buffer, alignment: number): Buffer {
    const remainder = data.length % alignment;
    if (remainder !== 0) {
        return Buffer.concat([data, Buffer.alloc(alignment - remainder)]);
    }
    return data;
}

/**
 * 字符串填充到指定对齐
 */
function padStringToAlignment(str: string, alignment: number): Buffer {
    const data = Buffer.from(str, 'utf-8');
    const remainder = data.length % alignment;
    if (remainder !== 0) {
        return Buffer.concat([data, Buffer.alloc(alignment - remainder)]);
    }
    return data;
}

/**
 * 文件节点
 */
class FileNode {
    constructor(
        public name: string,
        private data: Buffer
    ) {}

    get cName(): string {
        // 转换为合法的 C 标识符
        let name = this.name.replace(/[^a-zA-Z0-9]/g, '_');
        if (/^\d/.test(name)) {
            name = '_f_' + name;
        } else {
            name = '_' + name;
        }
        return name;
    }

    get binName(): Buffer {
        return padStringToAlignment(this.name, ALIGNMENT_4);
    }

    toCData(prefix: string = ''): string {
        const varName = prefix + this.cName;
        const bytes = Array.from(this.data).map(b => `0x${b.toString(16).padStart(2, '0')}`);
        return `static const uint8_t ${varName}[] = {\n${bytes.join(',')}\n};`;
    }

    get entrySize(): number {
        return this.data.length;
    }

    toBinary(): Buffer {
        return this.data;
    }
}

/**
 * 目录节点
 */
class FolderNode {
    public children: (FileNode | FolderNode)[] = [];

    constructor(public name: string) {}

    get cName(): string {
        let name = this.name.replace(/[^a-zA-Z0-9]/g, '_');
        if (/^\d/.test(name)) {
            name = '_d_' + name;
        } else {
            name = '_' + name;
        }
        return name;
    }

    addChild(child: FileNode | FolderNode): void {
        this.children.push(child);
    }

    sortChildren(): void {
        // 目录优先，然后按名称排序
        this.children.sort((a, b) => {
            const aIsFolder = a instanceof FolderNode;
            const bIsFolder = b instanceof FolderNode;
            if (aIsFolder !== bIsFolder) {
                return aIsFolder ? -1 : 1;
            }
            return a.name.localeCompare(b.name);
        });
        
        // 递归排序子目录
        this.children.forEach(child => {
            if (child instanceof FolderNode) {
                child.sortChildren();
            }
        });
    }
}

/**
 * 扫描目录构建文件树
 */
function scanDirectory(dirPath: string, name: string = ''): FolderNode {
    const folder = new FolderNode(name);
    const entries = fs.readdirSync(dirPath, { withFileTypes: true });

    for (const entry of entries) {
        const fullPath = path.join(dirPath, entry.name);
        
        if (entry.isDirectory()) {
            const subFolder = scanDirectory(fullPath, entry.name);
            folder.addChild(subFolder);
        } else if (entry.isFile()) {
            const data = fs.readFileSync(fullPath);
            const file = new FileNode(entry.name, data);
            folder.addChild(file);
        }
    }

    folder.sortChildren();
    return folder;
}

/**
 * 生成二进制 ROMFS
 */
function generateBinary(root: FolderNode, baseAddr: number): Buffer {
    const buffers: Buffer[] = [];
    
    // 递归收集所有文件数据
    function collectFileData(node: FolderNode | FileNode) {
        if (node instanceof FileNode) {
            // 文件名（对齐到 4 字节）
            buffers.push(node.binName);
            // 文件大小（4 字节）
            const sizeBuffer = Buffer.alloc(4);
            sizeBuffer.writeUInt32LE(node.entrySize, 0);
            buffers.push(sizeBuffer);
            // 文件数据（对齐到 64 字节）
            buffers.push(padToAlignment(node.toBinary(), ALIGNMENT_64));
        } else {
            node.children.forEach(collectFileData);
        }
    }
    
    collectFileData(root);
    
    return Buffer.concat(buffers);
}

/**
 * 生成 C 代码
 */
function generateCCode(root: FolderNode, baseAddr: number = 0): string {
    const lines: string[] = [];
    
    lines.push('/* Generated by mkromfs. Edit with caution. */');
    lines.push('#include "hg_romfs.h"');
    lines.push('');

    // 生成文件数据
    const files: FileNode[] = [];
    function collectFiles(node: FolderNode | FileNode) {
        if (node instanceof FileNode) {
            files.push(node);
        } else {
            node.children.forEach(collectFiles);
        }
    }
    collectFiles(root);

    files.forEach(file => {
        lines.push(file.toCData());
        lines.push('');
    });

    // 生成目录结构
    function generateDirents(node: FolderNode, prefix: string = ''): string {
        const dirLines: string[] = [];
        const varName = prefix + node.cName + '_children';
        
        dirLines.push(`static const struct romfs_dirent ${varName}[] = {`);
        
        node.children.forEach(child => {
            if (child instanceof FileNode) {
                dirLines.push(`    {ROMFS_DIRENT_FILE, "${child.name}", ${prefix}${child.cName}, ${child.entrySize}},`);
            } else {
                const childVarName = prefix + child.cName + '_children';
                dirLines.push(`    {ROMFS_DIRENT_DIR, "${child.name}", (const uint8_t *)${childVarName}, 0},`);
            }
        });
        
        dirLines.push('    {ROMFS_DIRENT_FILE, NULL, NULL, 0}');
        dirLines.push('};');
        
        return dirLines.join('\n');
    }

    // 递归生成所有目录
    function generateAllDirs(node: FolderNode, prefix: string = '') {
        node.children.forEach(child => {
            if (child instanceof FolderNode) {
                generateAllDirs(child, prefix);
            }
        });
        lines.push(generateDirents(node, prefix));
        lines.push('');
    }

    generateAllDirs(root);

    // 生成根节点
    const rootVarName = root.name ? `${root.name}_root` : 'app_romfs_root';
    lines.push(`const gui_fs_dirent_t *${rootVarName} = ${root.cName}_children;`);
    lines.push('');

    return lines.join('\n');
}

/**
 * 主函数
 */
export async function generateRomfs(options: RomfsOptions): Promise<void> {
    const { inputDir, outputFile, baseAddr = 0, binary = false } = options;

    if (!fs.existsSync(inputDir)) {
        throw new Error(`Input directory not found: ${inputDir}`);
    }

    // 扫描目录
    const root = scanDirectory(inputDir);

    if (binary) {
        // 生成二进制文件
        const binData = generateBinary(root, baseAddr);
        fs.writeFileSync(outputFile, binData);
    } else {
        // 生成 C 代码
        const code = generateCCode(root, baseAddr);
        fs.writeFileSync(outputFile, code, 'utf-8');
    }
}

/**
 * CLI 入口
 */
if (require.main === module) {
    const args = process.argv.slice(2);
    
    if (args.length < 4) {
        console.error('Usage: ts-node mkromfs.ts -i <input_dir> -o <output_file> [-a <base_addr>]');
        process.exit(1);
    }

    const options: RomfsOptions = {
        inputDir: '',
        outputFile: '',
        baseAddr: 0
    };

    for (let i = 0; i < args.length; i++) {
        if (args[i] === '-i' || args[i] === '--input') {
            options.inputDir = args[++i];
        } else if (args[i] === '-o' || args[i] === '--output') {
            options.outputFile = args[++i];
        } else if (args[i] === '-a' || args[i] === '--addr') {
            options.baseAddr = parseInt(args[++i], 16);
        } else if (args[i] === '-b' || args[i] === '--binary') {
            options.binary = true;
        }
    }

    generateRomfs(options)
        .then(() => console.log(`ROMFS generated: ${options.outputFile}`))
        .catch(err => {
            console.error('Error:', err.message);
            process.exit(1);
        });
}
