# building script for HoneyGUI

from building import *

cwd = GetCurrentDir()
CPPPATH = [
	cwd,
	cwd + '/firmware/include',
	cwd + '/firmware/src',
	cwd + '/firmware/sim',
 	cwd + '/firmware/external/stb',
]
src = Split("""
firmware/src/gps_driver.c
firmware/src/gps_provider.c
firmware/src/gps_simulator.c
firmware/src/lane_guidance.c
firmware/src/memory_monitor.c
firmware/src/nav_api.c
firmware/src/render_api.c
firmware/src/trvg/trvg.c
firmware/sim/app.c
""")

if GetDepend(['']):
	objs = DefineGroup('widget', src, depend = [''], CPPPATH = CPPPATH)
else:
	objs = []

Return('objs')


